// create object named "bankAccount"
// bankAccountID: which is autogenerated
// accountNumber: which is unique
// credentials: an array of Username, password, pin
// balance: amount of money
// createdAt: a date 


// object Bank Account
let bankAccount = {                     // string
    bankAccountID  : 0,                 // number
    accountNumber : 001112223333,       // number
    credentials : [                     // array open   
        userName = "JohnD",             // array string
        password = "Refocus63",         // array string
        pin =   1234                    // array number
        ],                              // array close
    balance : 2000,                     // number
    createdAt : "October 15th 2022"     // string
}

console.log(typeof bankAccount);
